[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "version-checker"
version = "0.0.0"
requires-python = ">=3.10"

dependencies = [
    "requests>=2.32.3",
    "packaging>=24.2"
]
