// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file nillion/payments/v1/config.proto (package nillion.payments.v1.config, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/payments/v1/config.proto.
 */
export const file_nillion_payments_v1_config: GenFile = /*@__PURE__*/
  fileDesc("CiBuaWxsaW9uL3BheW1lbnRzL3YxL2NvbmZpZy5wcm90bxIabmlsbGlvbi5wYXltZW50cy52MS5jb25maWciOwoWUGF5bWVudHNDb25maWdSZXNwb25zZRIhChltaW5pbXVtX2FkZF9mdW5kc19wYXltZW50GAEgASgEQrkBCh5jb20ubmlsbGlvbi5wYXltZW50cy52MS5jb25maWdCC0NvbmZpZ1Byb3RvUAGiAgROUFZDqgIaTmlsbGlvbi5QYXltZW50cy5WMS5Db25maWfKAhpOaWxsaW9uXFBheW1lbnRzXFYxXENvbmZpZ+ICJk5pbGxpb25cUGF5bWVudHNcVjFcQ29uZmlnXEdQQk1ldGFkYXRh6gIdTmlsbGlvbjo6UGF5bWVudHM6OlYxOjpDb25maWdiBnByb3RvMw");

/**
 * A response to a payments configuration request.
 *
 * @generated from message nillion.payments.v1.config.PaymentsConfigResponse
 */
export type PaymentsConfigResponse = Message<"nillion.payments.v1.config.PaymentsConfigResponse"> & {
  /**
   * The minimum amount of unil that can be added in a `Payments.add_funds` request.
   *
   * @generated from field: uint64 minimum_add_funds_payment = 1;
   */
  minimumAddFundsPayment: bigint;
};

/**
 * Describes the message nillion.payments.v1.config.PaymentsConfigResponse.
 * Use `create(PaymentsConfigResponseSchema)` to create a new message.
 */
export const PaymentsConfigResponseSchema: GenMessage<PaymentsConfigResponse> = /*@__PURE__*/
  messageDesc(file_nillion_payments_v1_config, 0);

