// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file nillion/payments/v1/config.proto (package nillion.payments.v1.config, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/payments/v1/config.proto.
 */
export const file_nillion_payments_v1_config: GenFile = /*@__PURE__*/
  fileDesc("CiBuaWxsaW9uL3BheW1lbnRzL3YxL2NvbmZpZy5wcm90bxIabmlsbGlvbi5wYXltZW50cy52MS5jb25maWciVAoWUGF5bWVudHNDb25maWdSZXNwb25zZRIhChltaW5pbXVtX2FkZF9mdW5kc19wYXltZW50GAEgASgEEhcKD2NyZWRpdHNfcGVyX25pbBgCIAEoBEK5AQoeY29tLm5pbGxpb24ucGF5bWVudHMudjEuY29uZmlnQgtDb25maWdQcm90b1ABogIETlBWQ6oCGk5pbGxpb24uUGF5bWVudHMuVjEuQ29uZmlnygIaTmlsbGlvblxQYXltZW50c1xWMVxDb25maWfiAiZOaWxsaW9uXFBheW1lbnRzXFYxXENvbmZpZ1xHUEJNZXRhZGF0YeoCHU5pbGxpb246OlBheW1lbnRzOjpWMTo6Q29uZmlnYgZwcm90bzM");

/**
 * A response to a payments configuration request.
 *
 * @generated from message nillion.payments.v1.config.PaymentsConfigResponse
 */
export type PaymentsConfigResponse = Message<"nillion.payments.v1.config.PaymentsConfigResponse"> & {
  /**
   * The minimum amount of unil that can be added in a `Payments.add_funds` request.
   *
   * @generated from field: uint64 minimum_add_funds_payment = 1;
   */
  minimumAddFundsPayment: bigint;

  /**
   * The number of credits one gets for every nil funded to an account.
   *
   * @generated from field: uint64 credits_per_nil = 2;
   */
  creditsPerNil: bigint;
};

/**
 * Describes the message nillion.payments.v1.config.PaymentsConfigResponse.
 * Use `create(PaymentsConfigResponseSchema)` to create a new message.
 */
export const PaymentsConfigResponseSchema: GenMessage<PaymentsConfigResponse> = /*@__PURE__*/
  messageDesc(file_nillion_payments_v1_config, 0);

