// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file nillion/payments/v1/service.proto (package nillion.payments.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { PriceQuoteRequestSchema, SignedQuoteSchema } from "./quote_pb";
import { file_nillion_payments_v1_quote } from "./quote_pb";
import type { PaymentReceiptRequestSchema, SignedReceiptSchema } from "./receipt_pb";
import { file_nillion_payments_v1_receipt } from "./receipt_pb";

/**
 * Describes the file nillion/payments/v1/service.proto.
 */
export const file_nillion_payments_v1_service: GenFile = /*@__PURE__*/
  fileDesc("CiFuaWxsaW9uL3BheW1lbnRzL3YxL3NlcnZpY2UucHJvdG8SE25pbGxpb24ucGF5bWVudHMudjEy4AEKCFBheW1lbnRzEmIKClByaWNlUXVvdGUSLC5uaWxsaW9uLnBheW1lbnRzLnYxLnF1b3RlLlByaWNlUXVvdGVSZXF1ZXN0GiYubmlsbGlvbi5wYXltZW50cy52MS5xdW90ZS5TaWduZWRRdW90ZRJwCg5QYXltZW50UmVjZWlwdBIyLm5pbGxpb24ucGF5bWVudHMudjEucmVjZWlwdC5QYXltZW50UmVjZWlwdFJlcXVlc3QaKi5uaWxsaW9uLnBheW1lbnRzLnYxLnJlY2VpcHQuU2lnbmVkUmVjZWlwdEKVAQoXY29tLm5pbGxpb24ucGF5bWVudHMudjFCDFNlcnZpY2VQcm90b1ABogIDTlBYqgITTmlsbGlvbi5QYXltZW50cy5WMcoCE05pbGxpb25cUGF5bWVudHNcVjHiAh9OaWxsaW9uXFBheW1lbnRzXFYxXEdQQk1ldGFkYXRh6gIVTmlsbGlvbjo6UGF5bWVudHM6OlYxYgZwcm90bzM", [file_nillion_payments_v1_quote, file_nillion_payments_v1_receipt]);

/**
 * Payments API.
 *
 * @generated from service nillion.payments.v1.Payments
 */
export const Payments: GenService<{
  /**
   * Generate a price quote for an operation.
   *
   * @generated from rpc nillion.payments.v1.Payments.PriceQuote
   */
  priceQuote: {
    methodKind: "unary";
    input: typeof PriceQuoteRequestSchema;
    output: typeof SignedQuoteSchema;
  },
  /**
   * Get a payment receipt for a paid operation.
   *
   * @generated from rpc nillion.payments.v1.Payments.PaymentReceipt
   */
  paymentReceipt: {
    methodKind: "unary";
    input: typeof PaymentReceiptRequestSchema;
    output: typeof SignedReceiptSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_nillion_payments_v1_service, 0);

