// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file nillion/leader_queries/v1/pool_status.proto (package nillion.leader_queries.v1.pool_status, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PreprocessingElement } from "../../preprocessing/v1/element_pb";
import { file_nillion_preprocessing_v1_element } from "../../preprocessing/v1/element_pb";
import type { SignedReceipt } from "../../payments/v1/receipt_pb";
import { file_nillion_payments_v1_receipt } from "../../payments/v1/receipt_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/leader_queries/v1/pool_status.proto.
 */
export const file_nillion_leader_queries_v1_pool_status: GenFile = /*@__PURE__*/
  fileDesc("CituaWxsaW9uL2xlYWRlcl9xdWVyaWVzL3YxL3Bvb2xfc3RhdHVzLnByb3RvEiVuaWxsaW9uLmxlYWRlcl9xdWVyaWVzLnYxLnBvb2xfc3RhdHVzIlcKEVBvb2xTdGF0dXNSZXF1ZXN0EkIKDnNpZ25lZF9yZWNlaXB0GAEgASgLMioubmlsbGlvbi5wYXltZW50cy52MS5yZWNlaXB0LlNpZ25lZFJlY2VpcHQipgEKElBvb2xTdGF0dXNSZXNwb25zZRJMCgdvZmZzZXRzGAEgAygLMjsubmlsbGlvbi5sZWFkZXJfcXVlcmllcy52MS5wb29sX3N0YXR1cy5QcmVwcm9jZXNzaW5nT2Zmc2V0cxIcChRwcmVwcm9jZXNzaW5nX2FjdGl2ZRgCIAEoCBIkChxhdXhpbGlhcnlfbWF0ZXJpYWxfYXZhaWxhYmxlGAMgASgIInsKFFByZXByb2Nlc3NpbmdPZmZzZXRzEkcKB2VsZW1lbnQYASABKA4yNi5uaWxsaW9uLnByZXByb2Nlc3NpbmcudjEuZWxlbWVudC5QcmVwcm9jZXNzaW5nRWxlbWVudBINCgVzdGFydBgCIAEoBBILCgNlbmQYAyABKARC7AEKKWNvbS5uaWxsaW9uLmxlYWRlcl9xdWVyaWVzLnYxLnBvb2xfc3RhdHVzQg9Qb29sU3RhdHVzUHJvdG9QAaICBE5MVlCqAiNOaWxsaW9uLkxlYWRlclF1ZXJpZXMuVjEuUG9vbFN0YXR1c8oCI05pbGxpb25cTGVhZGVyUXVlcmllc1xWMVxQb29sU3RhdHVz4gIvTmlsbGlvblxMZWFkZXJRdWVyaWVzXFYxXFBvb2xTdGF0dXNcR1BCTWV0YWRhdGHqAiZOaWxsaW9uOjpMZWFkZXJRdWVyaWVzOjpWMTo6UG9vbFN0YXR1c2IGcHJvdG8z", [file_nillion_preprocessing_v1_element, file_nillion_payments_v1_receipt]);

/**
 * A request to get the preprocessing pool status.
 *
 * @generated from message nillion.leader_queries.v1.pool_status.PoolStatusRequest
 */
export type PoolStatusRequest = Message<"nillion.leader_queries.v1.pool_status.PoolStatusRequest"> & {
  /**
   * The receipt that proves this operation was paid for.
   *
   * The receipt must be for a `PoolStatus` operation.
   *
   * @generated from field: nillion.payments.v1.receipt.SignedReceipt signed_receipt = 1;
   */
  signedReceipt?: SignedReceipt;
};

/**
 * Describes the message nillion.leader_queries.v1.pool_status.PoolStatusRequest.
 * Use `create(PoolStatusRequestSchema)` to create a new message.
 */
export const PoolStatusRequestSchema: GenMessage<PoolStatusRequest> = /*@__PURE__*/
  messageDesc(file_nillion_leader_queries_v1_pool_status, 0);

/**
 * A response for the request to get the status of the preprocessing pool.
 *
 * @generated from message nillion.leader_queries.v1.pool_status.PoolStatusResponse
 */
export type PoolStatusResponse = Message<"nillion.leader_queries.v1.pool_status.PoolStatusResponse"> & {
  /**
   * The offset ranges for each preprocessing element.
   *
   * @generated from field: repeated nillion.leader_queries.v1.pool_status.PreprocessingOffsets offsets = 1;
   */
  offsets: PreprocessingOffsets[];

  /**
   * Whether preprocessing is active (at least one element type is being generated).
   *
   * @generated from field: bool preprocessing_active = 2;
   */
  preprocessingActive: boolean;

  /**
   * Whether auxiliary material has been generated.
   *
   * @generated from field: bool auxiliary_material_available = 3;
   */
  auxiliaryMaterialAvailable: boolean;
};

/**
 * Describes the message nillion.leader_queries.v1.pool_status.PoolStatusResponse.
 * Use `create(PoolStatusResponseSchema)` to create a new message.
 */
export const PoolStatusResponseSchema: GenMessage<PoolStatusResponse> = /*@__PURE__*/
  messageDesc(file_nillion_leader_queries_v1_pool_status, 1);

/**
 * The offsets for a preprocessing element.
 *
 * This is closed-open set, e.g. [start, end)
 *
 * @generated from message nillion.leader_queries.v1.pool_status.PreprocessingOffsets
 */
export type PreprocessingOffsets = Message<"nillion.leader_queries.v1.pool_status.PreprocessingOffsets"> & {
  /**
   * The preprocessing element.
   *
   * @generated from field: nillion.preprocessing.v1.element.PreprocessingElement element = 1;
   */
  element: PreprocessingElement;

  /**
   * The first offset in the range.
   *
   * @generated from field: uint64 start = 2;
   */
  start: bigint;

  /**
   * The one-past-the-end offset in this range.
   *
   * @generated from field: uint64 end = 3;
   */
  end: bigint;
};

/**
 * Describes the message nillion.leader_queries.v1.pool_status.PreprocessingOffsets.
 * Use `create(PreprocessingOffsetsSchema)` to create a new message.
 */
export const PreprocessingOffsetsSchema: GenMessage<PreprocessingOffsets> = /*@__PURE__*/
  messageDesc(file_nillion_leader_queries_v1_pool_status, 2);

