// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/leader_queries/v1/service.proto (package nillion.leader_queries.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { PoolStatusRequestSchema, PoolStatusResponseSchema } from "./pool_status_pb";
import { file_nillion_leader_queries_v1_pool_status } from "./pool_status_pb";

/**
 * Describes the file nillion/leader_queries/v1/service.proto.
 */
export const file_nillion_leader_queries_v1_service: GenFile = /*@__PURE__*/
  fileDesc("CiduaWxsaW9uL2xlYWRlcl9xdWVyaWVzL3YxL3NlcnZpY2UucHJvdG8SGW5pbGxpb24ubGVhZGVyX3F1ZXJpZXMudjEykwEKDUxlYWRlclF1ZXJpZXMSgQEKClBvb2xTdGF0dXMSOC5uaWxsaW9uLmxlYWRlcl9xdWVyaWVzLnYxLnBvb2xfc3RhdHVzLlBvb2xTdGF0dXNSZXF1ZXN0GjkubmlsbGlvbi5sZWFkZXJfcXVlcmllcy52MS5wb29sX3N0YXR1cy5Qb29sU3RhdHVzUmVzcG9uc2VCrwEKHWNvbS5uaWxsaW9uLmxlYWRlcl9xdWVyaWVzLnYxQgxTZXJ2aWNlUHJvdG9QAaICA05MWKoCGE5pbGxpb24uTGVhZGVyUXVlcmllcy5WMcoCGE5pbGxpb25cTGVhZGVyUXVlcmllc1xWMeICJE5pbGxpb25cTGVhZGVyUXVlcmllc1xWMVxHUEJNZXRhZGF0YeoCGk5pbGxpb246OkxlYWRlclF1ZXJpZXM6OlYxYgZwcm90bzM", [file_nillion_leader_queries_v1_pool_status]);

/**
 * A service that allows performing queries against the leader of the cluster.
 *
 * @generated from service nillion.leader_queries.v1.LeaderQueries
 */
export const LeaderQueries: GenService<{
  /**
   * Get the status of the preprocessing pool.
   *
   * @generated from rpc nillion.leader_queries.v1.LeaderQueries.PoolStatus
   */
  poolStatus: {
    methodKind: "unary";
    input: typeof PoolStatusRequestSchema;
    output: typeof PoolStatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_nillion_leader_queries_v1_service, 0);

