// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file nillion/compute/v1/stream.proto (package nillion.compute.v1.stream, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/compute/v1/stream.proto.
 */
export const file_nillion_compute_v1_stream: GenFile = /*@__PURE__*/
  fileDesc("Ch9uaWxsaW9uL2NvbXB1dGUvdjEvc3RyZWFtLnByb3RvEhluaWxsaW9uLmNvbXB1dGUudjEuc3RyZWFtIkMKFENvbXB1dGVTdHJlYW1NZXNzYWdlEhIKCmNvbXB1dGVfaWQYASABKAwSFwoPYmluY29kZV9tZXNzYWdlGAIgASgMQrQBCh1jb20ubmlsbGlvbi5jb21wdXRlLnYxLnN0cmVhbUILU3RyZWFtUHJvdG9QAaICBE5DVlOqAhlOaWxsaW9uLkNvbXB1dGUuVjEuU3RyZWFtygIZTmlsbGlvblxDb21wdXRlXFYxXFN0cmVhbeICJU5pbGxpb25cQ29tcHV0ZVxWMVxTdHJlYW1cR1BCTWV0YWRhdGHqAhxOaWxsaW9uOjpDb21wdXRlOjpWMTo6U3RyZWFtYgZwcm90bzM");

/**
 * A message for a compute stream.
 *
 * @generated from message nillion.compute.v1.stream.ComputeStreamMessage
 */
export type ComputeStreamMessage = Message<"nillion.compute.v1.stream.ComputeStreamMessage"> & {
  /**
   * An identifier for the computation instance.
   *
   * Only the first ever message on the stream requires having this attribute set. Any subsequent message will
   * have this field ignored.
   *
   * @generated from field: bytes compute_id = 1;
   */
  computeId: Uint8Array;

  /**
   * The VM message in bincode format.
   *
   * @generated from field: bytes bincode_message = 2;
   */
  bincodeMessage: Uint8Array;
};

/**
 * Describes the message nillion.compute.v1.stream.ComputeStreamMessage.
 * Use `create(ComputeStreamMessageSchema)` to create a new message.
 */
export const ComputeStreamMessageSchema: GenMessage<ComputeStreamMessage> = /*@__PURE__*/
  messageDesc(file_nillion_compute_v1_stream, 0);

