// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/values/v1/delete.proto (package nillion.values.v1.delete, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/values/v1/delete.proto.
 */
export const file_nillion_values_v1_delete: GenFile = /*@__PURE__*/
  fileDesc("Ch5uaWxsaW9uL3ZhbHVlcy92MS9kZWxldGUucHJvdG8SGG5pbGxpb24udmFsdWVzLnYxLmRlbGV0ZSIoChNEZWxldGVWYWx1ZXNSZXF1ZXN0EhEKCXZhbHVlc19pZBgBIAEoDEKvAQocY29tLm5pbGxpb24udmFsdWVzLnYxLmRlbGV0ZUILRGVsZXRlUHJvdG9QAaICBE5WVkSqAhhOaWxsaW9uLlZhbHVlcy5WMS5EZWxldGXKAhhOaWxsaW9uXFZhbHVlc1xWMVxEZWxldGXiAiROaWxsaW9uXFZhbHVlc1xWMVxEZWxldGVcR1BCTWV0YWRhdGHqAhtOaWxsaW9uOjpWYWx1ZXM6OlYxOjpEZWxldGViBnByb3RvMw");

/**
 * A request to delete a previously stored set of values.
 *
 * @generated from message nillion.values.v1.delete.DeleteValuesRequest
 */
export type DeleteValuesRequest = Message<"nillion.values.v1.delete.DeleteValuesRequest"> & {
  /**
   * The identifier of the values entity to be deleted.
   *
   * @generated from field: bytes values_id = 1;
   */
  valuesId: Uint8Array;
};

/**
 * Describes the message nillion.values.v1.delete.DeleteValuesRequest.
 * Use `create(DeleteValuesRequestSchema)` to create a new message.
 */
export const DeleteValuesRequestSchema: GenMessage<DeleteValuesRequest> = /*@__PURE__*/
  messageDesc(file_nillion_values_v1_delete, 0);

