// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/values/v1/service.proto (package nillion.values.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { DeleteValuesRequestSchema } from "./delete_pb";
import { file_nillion_values_v1_delete } from "./delete_pb";
import type { RetrieveValuesRequestSchema, RetrieveValuesResponseSchema } from "./retrieve_pb";
import { file_nillion_values_v1_retrieve } from "./retrieve_pb";
import type { StoreValuesRequestSchema, StoreValuesResponseSchema } from "./store_pb";
import { file_nillion_values_v1_store } from "./store_pb";

/**
 * Describes the file nillion/values/v1/service.proto.
 */
export const file_nillion_values_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch9uaWxsaW9uL3ZhbHVlcy92MS9zZXJ2aWNlLnByb3RvEhFuaWxsaW9uLnZhbHVlcy52MTLCAgoGVmFsdWVzEmgKC1N0b3JlVmFsdWVzEisubmlsbGlvbi52YWx1ZXMudjEuc3RvcmUuU3RvcmVWYWx1ZXNSZXF1ZXN0GiwubmlsbGlvbi52YWx1ZXMudjEuc3RvcmUuU3RvcmVWYWx1ZXNSZXNwb25zZRJ3Cg5SZXRyaWV2ZVZhbHVlcxIxLm5pbGxpb24udmFsdWVzLnYxLnJldHJpZXZlLlJldHJpZXZlVmFsdWVzUmVxdWVzdBoyLm5pbGxpb24udmFsdWVzLnYxLnJldHJpZXZlLlJldHJpZXZlVmFsdWVzUmVzcG9uc2USVQoMRGVsZXRlVmFsdWVzEi0ubmlsbGlvbi52YWx1ZXMudjEuZGVsZXRlLkRlbGV0ZVZhbHVlc1JlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHlCiwEKFWNvbS5uaWxsaW9uLnZhbHVlcy52MUIMU2VydmljZVByb3RvUAGiAgNOVliqAhFOaWxsaW9uLlZhbHVlcy5WMcoCEU5pbGxpb25cVmFsdWVzXFYx4gIdTmlsbGlvblxWYWx1ZXNcVjFcR1BCTWV0YWRhdGHqAhNOaWxsaW9uOjpWYWx1ZXM6OlYxYgZwcm90bzM", [file_google_protobuf_empty, file_nillion_values_v1_delete, file_nillion_values_v1_retrieve, file_nillion_values_v1_store]);

/**
 * A service to interact with values (secrets, public values, etc).
 *
 * @generated from service nillion.values.v1.Values
 */
export const Values: GenService<{
  /**
   * Store values in the network.
   *
   * @generated from rpc nillion.values.v1.Values.StoreValues
   */
  storeValues: {
    methodKind: "unary";
    input: typeof StoreValuesRequestSchema;
    output: typeof StoreValuesResponseSchema;
  },
  /**
   * Retrieve values from the network.
   *
   * @generated from rpc nillion.values.v1.Values.RetrieveValues
   */
  retrieveValues: {
    methodKind: "unary";
    input: typeof RetrieveValuesRequestSchema;
    output: typeof RetrieveValuesResponseSchema;
  },
  /**
   * Delete values from the network.
   *
   * @generated from rpc nillion.values.v1.Values.DeleteValues
   */
  deleteValues: {
    methodKind: "unary";
    input: typeof DeleteValuesRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_nillion_values_v1_service, 0);

