// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/auth/v1/token.proto (package nillion.auth.v1.token, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { PublicKey } from "./public_key_pb";
import { file_nillion_auth_v1_public_key } from "./public_key_pb";
import type { NodeId } from "../../membership/v1/cluster_pb";
import { file_nillion_membership_v1_cluster } from "../../membership/v1/cluster_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/auth/v1/token.proto.
 */
export const file_nillion_auth_v1_token: GenFile = /*@__PURE__*/
  fileDesc("ChtuaWxsaW9uL2F1dGgvdjEvdG9rZW4ucHJvdG8SFW5pbGxpb24uYXV0aC52MS50b2tlbiJ1CgtTaWduZWRUb2tlbhIYChBzZXJpYWxpemVkX3Rva2VuGAEgASgMEjkKCnB1YmxpY19rZXkYAiABKAsyJS5uaWxsaW9uLmF1dGgudjEucHVibGljX2tleS5QdWJsaWNLZXkSEQoJc2lnbmF0dXJlGAMgASgMIoYBCgVUb2tlbhINCgVub25jZRgBIAEoDBI+Cg90YXJnZXRfaWRlbnRpdHkYAiABKAsyJS5uaWxsaW9uLm1lbWJlcnNoaXAudjEuY2x1c3Rlci5Ob2RlSWQSLgoKZXhwaXJlc19hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCnwEKGWNvbS5uaWxsaW9uLmF1dGgudjEudG9rZW5CClRva2VuUHJvdG9QAaICBE5BVlSqAhVOaWxsaW9uLkF1dGguVjEuVG9rZW7KAhVOaWxsaW9uXEF1dGhcVjFcVG9rZW7iAiFOaWxsaW9uXEF1dGhcVjFcVG9rZW5cR1BCTWV0YWRhdGHqAhhOaWxsaW9uOjpBdXRoOjpWMTo6VG9rZW5iBnByb3RvMw", [file_google_protobuf_timestamp, file_nillion_auth_v1_public_key, file_nillion_membership_v1_cluster]);

/**
 * A signed authentication token.
 *
 * @generated from message nillion.auth.v1.token.SignedToken
 */
export type SignedToken = Message<"nillion.auth.v1.token.SignedToken"> & {
  /**
   * A `Token` serialized into bytes.
   *
   * @generated from field: bytes serialized_token = 1;
   */
  serializedToken: Uint8Array;

  /**
   * The public key for the private key this token is signed with.
   *
   * @generated from field: nillion.auth.v1.public_key.PublicKey public_key = 2;
   */
  publicKey?: PublicKey;

  /**
   * The serialized token signature.
   *
   * The signature must be generated using the private key corresponding to the `public_key` field
   * over `sha256(serialized_token)`.
   *
   * @generated from field: bytes signature = 3;
   */
  signature: Uint8Array;
};

/**
 * Describes the message nillion.auth.v1.token.SignedToken.
 * Use `create(SignedTokenSchema)` to create a new message.
 */
export const SignedTokenSchema: GenMessage<SignedToken> = /*@__PURE__*/
  messageDesc(file_nillion_auth_v1_token, 0);

/**
 * A token.
 *
 * @generated from message nillion.auth.v1.token.Token
 */
export type Token = Message<"nillion.auth.v1.token.Token"> & {
  /**
   * A nonce that adds entropy to this token.
   *
   * The nonce must be 32 bytes long and will be considered invalid otherwise.
   *
   * @generated from field: bytes nonce = 1;
   */
  nonce: Uint8Array;

  /**
   * The identifier of the node this token is meant to be used against.
   *
   * This needs to match the target node's identity for the token to be considered valid, and is used to prevent
   * a node from taking the token and impersonating the user.
   *
   * @generated from field: nillion.membership.v1.cluster.NodeId target_identity = 2;
   */
  targetIdentity?: NodeId;

  /**
   * The timestamp at which this token expires.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;
};

/**
 * Describes the message nillion.auth.v1.token.Token.
 * Use `create(TokenSchema)` to create a new message.
 */
export const TokenSchema: GenMessage<Token> = /*@__PURE__*/
  messageDesc(file_nillion_auth_v1_token, 1);

