// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file nillion/auth/v1/user.proto (package nillion.auth.v1.user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/auth/v1/user.proto.
 */
export const file_nillion_auth_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChpuaWxsaW9uL2F1dGgvdjEvdXNlci5wcm90bxIUbmlsbGlvbi5hdXRoLnYxLnVzZXIiGgoGVXNlcklkEhAKCGNvbnRlbnRzGAEgASgMQpkBChhjb20ubmlsbGlvbi5hdXRoLnYxLnVzZXJCCVVzZXJQcm90b1ABogIETkFWVaoCFE5pbGxpb24uQXV0aC5WMS5Vc2VyygIUTmlsbGlvblxBdXRoXFYxXFVzZXLiAiBOaWxsaW9uXEF1dGhcVjFcVXNlclxHUEJNZXRhZGF0YeoCF05pbGxpb246OkF1dGg6OlYxOjpVc2VyYgZwcm90bzM");

/**
 * A user identifier.
 *
 * @generated from message nillion.auth.v1.user.UserId
 */
export type UserId = Message<"nillion.auth.v1.user.UserId"> & {
  /**
   * The contents of the user identifier.
   *
   * @generated from field: bytes contents = 1;
   */
  contents: Uint8Array;
};

/**
 * Describes the message nillion.auth.v1.user.UserId.
 * Use `create(UserIdSchema)` to create a new message.
 */
export const UserIdSchema: GenMessage<UserId> = /*@__PURE__*/
  messageDesc(file_nillion_auth_v1_user, 0);

