// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file nillion/preprocessing/v1/element.proto (package nillion.preprocessing.v1.element, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file nillion/preprocessing/v1/element.proto.
 */
export const file_nillion_preprocessing_v1_element: GenFile = /*@__PURE__*/
  fileDesc("CiZuaWxsaW9uL3ByZXByb2Nlc3NpbmcvdjEvZWxlbWVudC5wcm90bxIgbmlsbGlvbi5wcmVwcm9jZXNzaW5nLnYxLmVsZW1lbnQq8wEKFFByZXByb2Nlc3NpbmdFbGVtZW50EgkKBUFMUEhBEAASCgoGTEFNQkRBEAESCwoHQ09NUEFSRRACEhsKF0RJVklTSU9OX1NFQ1JFVF9ESVZJU09SEAMSGgoWRVFVQUxJVFlfU0VDUkVUX09VVFBVVBAEEhoKFkVRVUFMSVRZX1BVQkxJQ19PVVRQVVQQBRIVChFTSEFSRV9UT19QQVJUSUNMRRAGEgoKBk1PRFVMTxAHEgkKBVRSVU5DEAgSDAoIVFJVTkNfUFIQCRISCg5SQU5ET01fSU5URUdFUhAKEhIKDlJBTkRPTV9CT09MRUFOEAtC2AEKJGNvbS5uaWxsaW9uLnByZXByb2Nlc3NpbmcudjEuZWxlbWVudEIMRWxlbWVudFByb3RvUAGiAgROUFZFqgIgTmlsbGlvbi5QcmVwcm9jZXNzaW5nLlYxLkVsZW1lbnTKAiBOaWxsaW9uXFByZXByb2Nlc3NpbmdcVjFcRWxlbWVudOICLE5pbGxpb25cUHJlcHJvY2Vzc2luZ1xWMVxFbGVtZW50XEdQQk1ldGFkYXRh6gIjTmlsbGlvbjo6UHJlcHJvY2Vzc2luZzo6VjE6OkVsZW1lbnRiBnByb3RvMw");

/**
 * A preprocessing element.
 *
 * @generated from enum nillion.preprocessing.v1.element.PreprocessingElement
 */
export enum PreprocessingElement {
  /**
   * @generated from enum value: ALPHA = 0;
   */
  ALPHA = 0,

  /**
   * @generated from enum value: LAMBDA = 1;
   */
  LAMBDA = 1,

  /**
   * @generated from enum value: COMPARE = 2;
   */
  COMPARE = 2,

  /**
   * @generated from enum value: DIVISION_SECRET_DIVISOR = 3;
   */
  DIVISION_SECRET_DIVISOR = 3,

  /**
   * @generated from enum value: EQUALITY_SECRET_OUTPUT = 4;
   */
  EQUALITY_SECRET_OUTPUT = 4,

  /**
   * @generated from enum value: EQUALITY_PUBLIC_OUTPUT = 5;
   */
  EQUALITY_PUBLIC_OUTPUT = 5,

  /**
   * @generated from enum value: SHARE_TO_PARTICLE = 6;
   */
  SHARE_TO_PARTICLE = 6,

  /**
   * @generated from enum value: MODULO = 7;
   */
  MODULO = 7,

  /**
   * @generated from enum value: TRUNC = 8;
   */
  TRUNC = 8,

  /**
   * @generated from enum value: TRUNC_PR = 9;
   */
  TRUNC_PR = 9,

  /**
   * @generated from enum value: RANDOM_INTEGER = 10;
   */
  RANDOM_INTEGER = 10,

  /**
   * @generated from enum value: RANDOM_BOOLEAN = 11;
   */
  RANDOM_BOOLEAN = 11,
}

/**
 * Describes the enum nillion.preprocessing.v1.element.PreprocessingElement.
 */
export const PreprocessingElementSchema: GenEnum<PreprocessingElement> = /*@__PURE__*/
  enumDesc(file_nillion_preprocessing_v1_element, 0);

