// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file nillion/preprocessing/v1/material.proto (package nillion.preprocessing.v1.material, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file nillion/preprocessing/v1/material.proto.
 */
export const file_nillion_preprocessing_v1_material: GenFile = /*@__PURE__*/
  fileDesc("CiduaWxsaW9uL3ByZXByb2Nlc3NpbmcvdjEvbWF0ZXJpYWwucHJvdG8SIW5pbGxpb24ucHJlcHJvY2Vzc2luZy52MS5tYXRlcmlhbCovChFBdXhpbGlhcnlNYXRlcmlhbBIaChZDR0dNUDIxX0FVWElMSUFSWV9JTkZPEABC3gEKJWNvbS5uaWxsaW9uLnByZXByb2Nlc3NpbmcudjEubWF0ZXJpYWxCDU1hdGVyaWFsUHJvdG9QAaICBE5QVk2qAiFOaWxsaW9uLlByZXByb2Nlc3NpbmcuVjEuTWF0ZXJpYWzKAiFOaWxsaW9uXFByZXByb2Nlc3NpbmdcVjFcTWF0ZXJpYWziAi1OaWxsaW9uXFByZXByb2Nlc3NpbmdcVjFcTWF0ZXJpYWxcR1BCTWV0YWRhdGHqAiROaWxsaW9uOjpQcmVwcm9jZXNzaW5nOjpWMTo6TWF0ZXJpYWxiBnByb3RvMw");

/**
 * Auxiliary cluster material.
 *
 * @generated from enum nillion.preprocessing.v1.material.AuxiliaryMaterial
 */
export enum AuxiliaryMaterial {
  /**
   * ECDSA key generation auxiliary info as defined in the CGGMP21 paper.
   *
   * @generated from enum value: CGGMP21_AUXILIARY_INFO = 0;
   */
  CGGMP21_AUXILIARY_INFO = 0,
}

/**
 * Describes the enum nillion.preprocessing.v1.material.AuxiliaryMaterial.
 */
export const AuxiliaryMaterialSchema: GenEnum<AuxiliaryMaterial> = /*@__PURE__*/
  enumDesc(file_nillion_preprocessing_v1_material, 0);

