// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/preprocessing/v1/service.proto (package nillion.preprocessing.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { GeneratePreprocessingRequestSchema, GeneratePreprocessingResponseSchema } from "./generate_pb";
import { file_nillion_preprocessing_v1_generate } from "./generate_pb";
import type { PreprocessingStreamMessageSchema } from "./stream_pb";
import { file_nillion_preprocessing_v1_stream } from "./stream_pb";
import type { CleanupUsedElementsRequestSchema } from "./cleanup_pb";
import { file_nillion_preprocessing_v1_cleanup } from "./cleanup_pb";

/**
 * Describes the file nillion/preprocessing/v1/service.proto.
 */
export const file_nillion_preprocessing_v1_service: GenFile = /*@__PURE__*/
  fileDesc("CiZuaWxsaW9uL3ByZXByb2Nlc3NpbmcvdjEvc2VydmljZS5wcm90bxIYbmlsbGlvbi5wcmVwcm9jZXNzaW5nLnYxMokDCg1QcmVwcm9jZXNzaW5nEpwBChVHZW5lcmF0ZVByZXByb2Nlc3NpbmcSPy5uaWxsaW9uLnByZXByb2Nlc3NpbmcudjEuZ2VuZXJhdGUuR2VuZXJhdGVQcmVwcm9jZXNzaW5nUmVxdWVzdBpALm5pbGxpb24ucHJlcHJvY2Vzc2luZy52MS5nZW5lcmF0ZS5HZW5lcmF0ZVByZXByb2Nlc3NpbmdSZXNwb25zZTABEmwKE1N0cmVhbVByZXByb2Nlc3NpbmcSOy5uaWxsaW9uLnByZXByb2Nlc3NpbmcudjEuc3RyZWFtLlByZXByb2Nlc3NpbmdTdHJlYW1NZXNzYWdlGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5KAESawoTQ2xlYW51cFVzZWRFbGVtZW50cxI8Lm5pbGxpb24ucHJlcHJvY2Vzc2luZy52MS5jbGVhbnVwLkNsZWFudXBVc2VkRWxlbWVudHNSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Qq4BChxjb20ubmlsbGlvbi5wcmVwcm9jZXNzaW5nLnYxQgxTZXJ2aWNlUHJvdG9QAaICA05QWKoCGE5pbGxpb24uUHJlcHJvY2Vzc2luZy5WMcoCGE5pbGxpb25cUHJlcHJvY2Vzc2luZ1xWMeICJE5pbGxpb25cUHJlcHJvY2Vzc2luZ1xWMVxHUEJNZXRhZGF0YeoCGk5pbGxpb246OlByZXByb2Nlc3Npbmc6OlYxYgZwcm90bzM", [file_google_protobuf_empty, file_nillion_preprocessing_v1_generate, file_nillion_preprocessing_v1_stream, file_nillion_preprocessing_v1_cleanup]);

/**
 * A service to run preprocessing related actions.
 *
 * @generated from service nillion.preprocessing.v1.Preprocessing
 */
export const Preprocessing: GenService<{
  /**
   * Trigger the generation of preprocessing material.
   *
   * @generated from rpc nillion.preprocessing.v1.Preprocessing.GeneratePreprocessing
   */
  generatePreprocessing: {
    methodKind: "server_streaming";
    input: typeof GeneratePreprocessingRequestSchema;
    output: typeof GeneratePreprocessingResponseSchema;
  },
  /**
   * Open a stream to generate a preprocessing element.
   *
   * @generated from rpc nillion.preprocessing.v1.Preprocessing.StreamPreprocessing
   */
  streamPreprocessing: {
    methodKind: "client_streaming";
    input: typeof PreprocessingStreamMessageSchema;
    output: typeof EmptySchema;
  },
  /**
   * Cleanup used preprocessing chunks.
   *
   * @generated from rpc nillion.preprocessing.v1.Preprocessing.CleanupUsedElements
   */
  cleanupUsedElements: {
    methodKind: "unary";
    input: typeof CleanupUsedElementsRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_nillion_preprocessing_v1_service, 0);

