// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/preprocessing/v1/stream.proto (package nillion.preprocessing.v1.stream, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PreprocessingElement } from "./element_pb";
import { file_nillion_preprocessing_v1_element } from "./element_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/preprocessing/v1/stream.proto.
 */
export const file_nillion_preprocessing_v1_stream: GenFile = /*@__PURE__*/
  fileDesc("CiVuaWxsaW9uL3ByZXByb2Nlc3NpbmcvdjEvc3RyZWFtLnByb3RvEh9uaWxsaW9uLnByZXByb2Nlc3NpbmcudjEuc3RyZWFtIpUBChpQcmVwcm9jZXNzaW5nU3RyZWFtTWVzc2FnZRIVCg1nZW5lcmF0aW9uX2lkGAEgASgMEkcKB2VsZW1lbnQYAiABKA4yNi5uaWxsaW9uLnByZXByb2Nlc3NpbmcudjEuZWxlbWVudC5QcmVwcm9jZXNzaW5nRWxlbWVudBIXCg9iaW5jb2RlX21lc3NhZ2UYAyABKAxC0gEKI2NvbS5uaWxsaW9uLnByZXByb2Nlc3NpbmcudjEuc3RyZWFtQgtTdHJlYW1Qcm90b1ABogIETlBWU6oCH05pbGxpb24uUHJlcHJvY2Vzc2luZy5WMS5TdHJlYW3KAh9OaWxsaW9uXFByZXByb2Nlc3NpbmdcVjFcU3RyZWFt4gIrTmlsbGlvblxQcmVwcm9jZXNzaW5nXFYxXFN0cmVhbVxHUEJNZXRhZGF0YeoCIk5pbGxpb246OlByZXByb2Nlc3Npbmc6OlYxOjpTdHJlYW1iBnByb3RvMw", [file_nillion_preprocessing_v1_element]);

/**
 * A message sent between nodes during the execution of a preprocessing protocol.
 *
 * @generated from message nillion.preprocessing.v1.stream.PreprocessingStreamMessage
 */
export type PreprocessingStreamMessage = Message<"nillion.preprocessing.v1.stream.PreprocessingStreamMessage"> & {
  /**
   * An identifier for the instance of the generation being ran.
   *
   * Only the first ever message on the stream requires having this attribute set. Any subsequent message will
   * have this field ignored.
   *
   * @generated from field: bytes generation_id = 1;
   */
  generationId: Uint8Array;

  /**
   * The element being generated.
   *
   * Only the first ever message on the stream requires having this attribute set. Any subsequent message will
   * have this field ignored.
   *
   * @generated from field: nillion.preprocessing.v1.element.PreprocessingElement element = 2;
   */
  element: PreprocessingElement;

  /**
   * The preprocessing message in bincode format.
   *
   * @generated from field: bytes bincode_message = 3;
   */
  bincodeMessage: Uint8Array;
};

/**
 * Describes the message nillion.preprocessing.v1.stream.PreprocessingStreamMessage.
 * Use `create(PreprocessingStreamMessageSchema)` to create a new message.
 */
export const PreprocessingStreamMessageSchema: GenMessage<PreprocessingStreamMessage> = /*@__PURE__*/
  messageDesc(file_nillion_preprocessing_v1_stream, 0);

