// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/programs/v1/service.proto (package nillion.programs.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { StoreProgramRequestSchema, StoreProgramResponseSchema } from "./store_pb";
import { file_nillion_programs_v1_store } from "./store_pb";

/**
 * Describes the file nillion/programs/v1/service.proto.
 */
export const file_nillion_programs_v1_service: GenFile = /*@__PURE__*/
  fileDesc("CiFuaWxsaW9uL3Byb2dyYW1zL3YxL3NlcnZpY2UucHJvdG8SE25pbGxpb24ucHJvZ3JhbXMudjEyewoIUHJvZ3JhbXMSbwoMU3RvcmVQcm9ncmFtEi4ubmlsbGlvbi5wcm9ncmFtcy52MS5zdG9yZS5TdG9yZVByb2dyYW1SZXF1ZXN0Gi8ubmlsbGlvbi5wcm9ncmFtcy52MS5zdG9yZS5TdG9yZVByb2dyYW1SZXNwb25zZUKVAQoXY29tLm5pbGxpb24ucHJvZ3JhbXMudjFCDFNlcnZpY2VQcm90b1ABogIDTlBYqgITTmlsbGlvbi5Qcm9ncmFtcy5WMcoCE05pbGxpb25cUHJvZ3JhbXNcVjHiAh9OaWxsaW9uXFByb2dyYW1zXFYxXEdQQk1ldGFkYXRh6gIVTmlsbGlvbjo6UHJvZ3JhbXM6OlYxYgZwcm90bzM", [file_nillion_programs_v1_store]);

/**
 * A service to manage programs.
 *
 * @generated from service nillion.programs.v1.Programs
 */
export const Programs: GenService<{
  /**
   * Store a program in the network.
   *
   * @generated from rpc nillion.programs.v1.Programs.StoreProgram
   */
  storeProgram: {
    methodKind: "unary";
    input: typeof StoreProgramRequestSchema;
    output: typeof StoreProgramResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_nillion_programs_v1_service, 0);

