// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file nillion/membership/v1/version.proto (package nillion.membership.v1.version, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/membership/v1/version.proto.
 */
export const file_nillion_membership_v1_version: GenFile = /*@__PURE__*/
  fileDesc("CiNuaWxsaW9uL21lbWJlcnNoaXAvdjEvdmVyc2lvbi5wcm90bxIdbmlsbGlvbi5tZW1iZXJzaGlwLnYxLnZlcnNpb24iXgoLTm9kZVZlcnNpb24SPQoHdmVyc2lvbhgBIAEoCzIsLm5pbGxpb24ubWVtYmVyc2hpcC52MS52ZXJzaW9uLlNlbXZlclZlcnNpb24SEAoIZ2l0X2hhc2gYAiABKAkiUQoNU2VtdmVyVmVyc2lvbhINCgVtYWpvchgBIAEoBBINCgVtaW5vchgCIAEoBBINCgVwYXRjaBgDIAEoBBITCgtwcmVfcmVsZWFzZRgEIAEoCULJAQohY29tLm5pbGxpb24ubWVtYmVyc2hpcC52MS52ZXJzaW9uQgxWZXJzaW9uUHJvdG9QAaICBE5NVlaqAh1OaWxsaW9uLk1lbWJlcnNoaXAuVjEuVmVyc2lvbsoCHU5pbGxpb25cTWVtYmVyc2hpcFxWMVxWZXJzaW9u4gIpTmlsbGlvblxNZW1iZXJzaGlwXFYxXFZlcnNpb25cR1BCTWV0YWRhdGHqAiBOaWxsaW9uOjpNZW1iZXJzaGlwOjpWMTo6VmVyc2lvbmIGcHJvdG8z");

/**
 * The node's version.
 *
 * @generated from message nillion.membership.v1.version.NodeVersion
 */
export type NodeVersion = Message<"nillion.membership.v1.version.NodeVersion"> & {
  /**
   * The node's version.
   *
   * @generated from field: nillion.membership.v1.version.SemverVersion version = 1;
   */
  version?: SemverVersion;

  /**
   * The built git commit hash.
   *
   * @generated from field: string git_hash = 2;
   */
  gitHash: string;
};

/**
 * Describes the message nillion.membership.v1.version.NodeVersion.
 * Use `create(NodeVersionSchema)` to create a new message.
 */
export const NodeVersionSchema: GenMessage<NodeVersion> = /*@__PURE__*/
  messageDesc(file_nillion_membership_v1_version, 0);

/**
 * A semver version.
 *
 * @generated from message nillion.membership.v1.version.SemverVersion
 */
export type SemverVersion = Message<"nillion.membership.v1.version.SemverVersion"> & {
  /**
   * The major version.
   *
   * @generated from field: uint64 major = 1;
   */
  major: bigint;

  /**
   * The minor version.
   *
   * @generated from field: uint64 minor = 2;
   */
  minor: bigint;

  /**
   * The patch version.
   *
   * @generated from field: uint64 patch = 3;
   */
  patch: bigint;

  /**
   * The optional pre-release version.
   *
   * @generated from field: string pre_release = 4;
   */
  preRelease: string;
};

/**
 * Describes the message nillion.membership.v1.version.SemverVersion.
 * Use `create(SemverVersionSchema)` to create a new message.
 */
export const SemverVersionSchema: GenMessage<SemverVersion> = /*@__PURE__*/
  messageDesc(file_nillion_membership_v1_version, 1);

