// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file nillion/permissions/v1/overwrite.proto (package nillion.permissions.v1.overwrite, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { SignedReceipt } from "../../payments/v1/receipt_pb";
import { file_nillion_payments_v1_receipt } from "../../payments/v1/receipt_pb";
import type { Permissions } from "./permissions_pb";
import { file_nillion_permissions_v1_permissions } from "./permissions_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/permissions/v1/overwrite.proto.
 */
export const file_nillion_permissions_v1_overwrite: GenFile = /*@__PURE__*/
  fileDesc("CiZuaWxsaW9uL3Blcm1pc3Npb25zL3YxL292ZXJ3cml0ZS5wcm90bxIgbmlsbGlvbi5wZXJtaXNzaW9ucy52MS5vdmVyd3JpdGUipwEKG092ZXJ3cml0ZVBlcm1pc3Npb25zUmVxdWVzdBJCCg5zaWduZWRfcmVjZWlwdBgBIAEoCzIqLm5pbGxpb24ucGF5bWVudHMudjEucmVjZWlwdC5TaWduZWRSZWNlaXB0EkQKC3Blcm1pc3Npb25zGAIgASgLMi8ubmlsbGlvbi5wZXJtaXNzaW9ucy52MS5wZXJtaXNzaW9ucy5QZXJtaXNzaW9uc0LaAQokY29tLm5pbGxpb24ucGVybWlzc2lvbnMudjEub3ZlcndyaXRlQg5PdmVyd3JpdGVQcm90b1ABogIETlBWT6oCIE5pbGxpb24uUGVybWlzc2lvbnMuVjEuT3ZlcndyaXRlygIgTmlsbGlvblxQZXJtaXNzaW9uc1xWMVxPdmVyd3JpdGXiAixOaWxsaW9uXFBlcm1pc3Npb25zXFYxXE92ZXJ3cml0ZVxHUEJNZXRhZGF0YeoCI05pbGxpb246OlBlcm1pc3Npb25zOjpWMTo6T3ZlcndyaXRlYgZwcm90bzM", [file_nillion_payments_v1_receipt, file_nillion_permissions_v1_permissions]);

/**
 * A request to overwrite the permissions associated with a set of previously stored values.
 *
 * @generated from message nillion.permissions.v1.overwrite.OverwritePermissionsRequest
 */
export type OverwritePermissionsRequest = Message<"nillion.permissions.v1.overwrite.OverwritePermissionsRequest"> & {
  /**
   * The receipt that proves this operation was paid for.
   *
   * The receipt must be for a `UpdatePermissions` operation.
   *
   * @generated from field: nillion.payments.v1.receipt.SignedReceipt signed_receipt = 1;
   */
  signedReceipt?: SignedReceipt;

  /**
   * The permissions to be set.
   *
   * The permissions will be overridden with these, so whatever permissions the values being updated
   * had before will no longer exist.
   *
   * @generated from field: nillion.permissions.v1.permissions.Permissions permissions = 2;
   */
  permissions?: Permissions;
};

/**
 * Describes the message nillion.permissions.v1.overwrite.OverwritePermissionsRequest.
 * Use `create(OverwritePermissionsRequestSchema)` to create a new message.
 */
export const OverwritePermissionsRequestSchema: GenMessage<OverwritePermissionsRequest> = /*@__PURE__*/
  messageDesc(file_nillion_permissions_v1_overwrite, 0);

