// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/permissions/v1/permissions.proto (package nillion.permissions.v1.permissions, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/permissions/v1/permissions.proto.
 */
export const file_nillion_permissions_v1_permissions: GenFile = /*@__PURE__*/
  fileDesc("CihuaWxsaW9uL3Blcm1pc3Npb25zL3YxL3Blcm1pc3Npb25zLnByb3RvEiJuaWxsaW9uLnBlcm1pc3Npb25zLnYxLnBlcm1pc3Npb25zIt4BCgtQZXJtaXNzaW9ucxIVCg1vd25lcl91c2VyX2lkGAEgASgJEiEKGXJldHJpZXZlX2FsbG93ZWRfdXNlcl9pZHMYAiADKAkSHwoXdXBkYXRlX2FsbG93ZWRfdXNlcl9pZHMYAyADKAkSHwoXZGVsZXRlX2FsbG93ZWRfdXNlcl9pZHMYBCADKAkSUwoTY29tcHV0ZV9wZXJtaXNzaW9ucxgFIAMoCzI2Lm5pbGxpb24ucGVybWlzc2lvbnMudjEucGVybWlzc2lvbnMuQ29tcHV0ZVBlcm1pc3Npb25zIjoKEkNvbXB1dGVQZXJtaXNzaW9ucxIPCgd1c2VyX2lkGAEgASgJEhMKC3Byb2dyYW1faWRzGAIgAygJQuYBCiZjb20ubmlsbGlvbi5wZXJtaXNzaW9ucy52MS5wZXJtaXNzaW9uc0IQUGVybWlzc2lvbnNQcm90b1ABogIETlBWUKoCIk5pbGxpb24uUGVybWlzc2lvbnMuVjEuUGVybWlzc2lvbnPKAiJOaWxsaW9uXFBlcm1pc3Npb25zXFYxXFBlcm1pc3Npb25z4gIuTmlsbGlvblxQZXJtaXNzaW9uc1xWMVxQZXJtaXNzaW9uc1xHUEJNZXRhZGF0YeoCJU5pbGxpb246OlBlcm1pc3Npb25zOjpWMTo6UGVybWlzc2lvbnNiBnByb3RvMw");

/**
 * The permissions for a set of stored values.
 *
 * @generated from message nillion.permissions.v1.permissions.Permissions
 */
export type Permissions = Message<"nillion.permissions.v1.permissions.Permissions"> & {
  /**
   * The user id for the owner of these values.
   *
   * @generated from field: string owner_user_id = 1;
   */
  ownerUserId: string;

  /**
   * The list of user ids that are allowed to retrieve the stored values.
   *
   * @generated from field: repeated string retrieve_allowed_user_ids = 2;
   */
  retrieveAllowedUserIds: string[];

  /**
   * The list of user ids that are allowed to update the stored values.
   *
   * @generated from field: repeated string update_allowed_user_ids = 3;
   */
  updateAllowedUserIds: string[];

  /**
   * The list of user ids that are allowed to delete the stored values.
   *
   * @generated from field: repeated string delete_allowed_user_ids = 4;
   */
  deleteAllowedUserIds: string[];

  /**
   * The list of compute permissions.
   *
   * @generated from field: repeated nillion.permissions.v1.permissions.ComputePermissions compute_permissions = 5;
   */
  computePermissions: ComputePermissions[];
};

/**
 * Describes the message nillion.permissions.v1.permissions.Permissions.
 * Use `create(PermissionsSchema)` to create a new message.
 */
export const PermissionsSchema: GenMessage<Permissions> = /*@__PURE__*/
  messageDesc(file_nillion_permissions_v1_permissions, 0);

/**
 * The permissions to execute a program.
 *
 * @generated from message nillion.permissions.v1.permissions.ComputePermissions
 */
export type ComputePermissions = Message<"nillion.permissions.v1.permissions.ComputePermissions"> & {
  /**
   * The user id we're granting permissions to.
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * The program ids this user is allowed to use the stored values in.
   *
   * @generated from field: repeated string program_ids = 2;
   */
  programIds: string[];
};

/**
 * Describes the message nillion.permissions.v1.permissions.ComputePermissions.
 * Use `create(ComputePermissionsSchema)` to create a new message.
 */
export const ComputePermissionsSchema: GenMessage<ComputePermissions> = /*@__PURE__*/
  messageDesc(file_nillion_permissions_v1_permissions, 1);

