// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file nillion/permissions/v1/retrieve.proto (package nillion.permissions.v1.retrieve, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { SignedReceipt } from "../../payments/v1/receipt_pb";
import { file_nillion_payments_v1_receipt } from "../../payments/v1/receipt_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/permissions/v1/retrieve.proto.
 */
export const file_nillion_permissions_v1_retrieve: GenFile = /*@__PURE__*/
  fileDesc("CiVuaWxsaW9uL3Blcm1pc3Npb25zL3YxL3JldHJpZXZlLnByb3RvEh9uaWxsaW9uLnBlcm1pc3Npb25zLnYxLnJldHJpZXZlImAKGlJldHJpZXZlUGVybWlzc2lvbnNSZXF1ZXN0EkIKDnNpZ25lZF9yZWNlaXB0GAEgASgLMioubmlsbGlvbi5wYXltZW50cy52MS5yZWNlaXB0LlNpZ25lZFJlY2VpcHRC1AEKI2NvbS5uaWxsaW9uLnBlcm1pc3Npb25zLnYxLnJldHJpZXZlQg1SZXRyaWV2ZVByb3RvUAGiAgROUFZSqgIfTmlsbGlvbi5QZXJtaXNzaW9ucy5WMS5SZXRyaWV2ZcoCH05pbGxpb25cUGVybWlzc2lvbnNcVjFcUmV0cmlldmXiAitOaWxsaW9uXFBlcm1pc3Npb25zXFYxXFJldHJpZXZlXEdQQk1ldGFkYXRh6gIiTmlsbGlvbjo6UGVybWlzc2lvbnM6OlYxOjpSZXRyaWV2ZWIGcHJvdG8z", [file_nillion_payments_v1_receipt]);

/**
 * A request to retrieve the permissions associated with a set of previously stored values.
 *
 * @generated from message nillion.permissions.v1.retrieve.RetrievePermissionsRequest
 */
export type RetrievePermissionsRequest = Message<"nillion.permissions.v1.retrieve.RetrievePermissionsRequest"> & {
  /**
   * The receipt that proves this operation was paid for.
   *
   * The receipt must be for a `RetrievePermissions` operation.
   *
   * @generated from field: nillion.payments.v1.receipt.SignedReceipt signed_receipt = 1;
   */
  signedReceipt?: SignedReceipt;
};

/**
 * Describes the message nillion.permissions.v1.retrieve.RetrievePermissionsRequest.
 * Use `create(RetrievePermissionsRequestSchema)` to create a new message.
 */
export const RetrievePermissionsRequestSchema: GenMessage<RetrievePermissionsRequest> = /*@__PURE__*/
  messageDesc(file_nillion_permissions_v1_retrieve, 0);

