// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/permissions/v1/update.proto (package nillion.permissions.v1.update, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { SignedReceipt } from "../../payments/v1/receipt_pb";
import { file_nillion_payments_v1_receipt } from "../../payments/v1/receipt_pb";
import type { Permissions } from "./permissions_pb";
import { file_nillion_permissions_v1_permissions } from "./permissions_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/permissions/v1/update.proto.
 */
export const file_nillion_permissions_v1_update: GenFile = /*@__PURE__*/
  fileDesc("CiNuaWxsaW9uL3Blcm1pc3Npb25zL3YxL3VwZGF0ZS5wcm90bxIdbmlsbGlvbi5wZXJtaXNzaW9ucy52MS51cGRhdGUipAEKGFVwZGF0ZVBlcm1pc3Npb25zUmVxdWVzdBJCCg5zaWduZWRfcmVjZWlwdBgBIAEoCzIqLm5pbGxpb24ucGF5bWVudHMudjEucmVjZWlwdC5TaWduZWRSZWNlaXB0EkQKC3Blcm1pc3Npb25zGAIgASgLMi8ubmlsbGlvbi5wZXJtaXNzaW9ucy52MS5wZXJtaXNzaW9ucy5QZXJtaXNzaW9uc0LIAQohY29tLm5pbGxpb24ucGVybWlzc2lvbnMudjEudXBkYXRlQgtVcGRhdGVQcm90b1ABogIETlBWVaoCHU5pbGxpb24uUGVybWlzc2lvbnMuVjEuVXBkYXRlygIdTmlsbGlvblxQZXJtaXNzaW9uc1xWMVxVcGRhdGXiAilOaWxsaW9uXFBlcm1pc3Npb25zXFYxXFVwZGF0ZVxHUEJNZXRhZGF0YeoCIE5pbGxpb246OlBlcm1pc3Npb25zOjpWMTo6VXBkYXRlYgZwcm90bzM", [file_nillion_payments_v1_receipt, file_nillion_permissions_v1_permissions]);

/**
 * A request to update the permissions associated with a set of previously stored values.
 *
 * @generated from message nillion.permissions.v1.update.UpdatePermissionsRequest
 */
export type UpdatePermissionsRequest = Message<"nillion.permissions.v1.update.UpdatePermissionsRequest"> & {
  /**
   * The receipt that proves this operation was paid for.
   *
   * The receipt must be for a `UpdatePermissions` operation.
   *
   * @generated from field: nillion.payments.v1.receipt.SignedReceipt signed_receipt = 1;
   */
  signedReceipt?: SignedReceipt;

  /**
   * @generated from field: nillion.permissions.v1.permissions.Permissions permissions = 2;
   */
  permissions?: Permissions;
};

/**
 * Describes the message nillion.permissions.v1.update.UpdatePermissionsRequest.
 * Use `create(UpdatePermissionsRequestSchema)` to create a new message.
 */
export const UpdatePermissionsRequestSchema: GenMessage<UpdatePermissionsRequest> = /*@__PURE__*/
  messageDesc(file_nillion_permissions_v1_update, 0);

