// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file nillion/meta/v1/msg_pay_for.proto (package nillion.meta.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file nillion/meta/v1/msg_pay_for.proto.
 */
export const file_nillion_meta_v1_msg_pay_for: GenFile = /*@__PURE__*/
  fileDesc("CiFuaWxsaW9uL21ldGEvdjEvbXNnX3BheV9mb3IucHJvdG8SD25pbGxpb24ubWV0YS52MSJcCglNc2dQYXlGb3ISEAoIcmVzb3VyY2UYASABKAwSFAoMZnJvbV9hZGRyZXNzGAIgASgJEicKBmFtb3VudBgDIAMoCzIXLm5pbGxpb24ubWV0YS52MS5BbW91bnQiJwoGQW1vdW50Eg0KBWRlbm9tGAEgASgJEg4KBmFtb3VudBgCIAEoCUKDAQoTY29tLm5pbGxpb24ubWV0YS52MUIOTXNnUGF5Rm9yUHJvdG9QAaICA05NWKoCD05pbGxpb24uTWV0YS5WMcoCD05pbGxpb25cTWV0YVxWMeICG05pbGxpb25cTWV0YVxWMVxHUEJNZXRhZGF0YeoCEU5pbGxpb246Ok1ldGE6OlYxYgZwcm90bzM");

/**
 * @generated from message nillion.meta.v1.MsgPayFor
 */
export type MsgPayFor = Message<"nillion.meta.v1.MsgPayFor"> & {
  /**
   * @generated from field: bytes resource = 1;
   */
  resource: Uint8Array;

  /**
   * @generated from field: string from_address = 2;
   */
  fromAddress: string;

  /**
   * @generated from field: repeated nillion.meta.v1.Amount amount = 3;
   */
  amount: Amount[];
};

/**
 * Describes the message nillion.meta.v1.MsgPayFor.
 * Use `create(MsgPayForSchema)` to create a new message.
 */
export const MsgPayForSchema: GenMessage<MsgPayFor> = /*@__PURE__*/
  messageDesc(file_nillion_meta_v1_msg_pay_for, 0);

/**
 * @generated from message nillion.meta.v1.Amount
 */
export type Amount = Message<"nillion.meta.v1.Amount"> & {
  /**
   * @generated from field: string denom = 1;
   */
  denom: string;

  /**
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message nillion.meta.v1.Amount.
 * Use `create(AmountSchema)` to create a new message.
 */
export const AmountSchema: GenMessage<Amount> = /*@__PURE__*/
  messageDesc(file_nillion_meta_v1_msg_pay_for, 1);

